### ISSUE TITLE
R - for RTK showing inappropriately

### ISSUE THREAD

**Issue by Djacob502** [dji-sdk/Mobile-UILibrary-Android#10]
The GPS signal widget shows a small 'r' for rtk enabled even if rtk is not enabled. 

Also another small item. In the camera control widget - the menu button, at the top of the control, text color is black making this very hard to see. The color should default to white or near white to match the bottom button used to control the exposure settings. 

Using ui library 4.1.1
Phantom 4 pro
Android 7
nVidia k1 shield
Android 2.3

**Comment by zoemcateedji** [comment]
Checked with the 4.3.2 sample app of the UI Library and the R isn't there on the Phantom 4 pro.  Please take a screen cap if you see it in the 4.3.2 version.

For your second issue, the word "Menu" is gray on a dark gray button- that is our neutral design to work with light or dark backgrounds.  If you are referring to something else please take a screen capture in our sample app.

Thanks!

**Comment by zoemcateedji** [comment]
I wanted to update you that we did see the black issue - it's device specific.  It will be fixed in our next release.
Thanks for letting us know!

**Comment by Djacob502** [comment]
Thanks for getting this corrected.
