### ISSUE TITLE
dji.ui.panel.CameraSettingExposurePanel - aperture not working correctly

### ISSUE THREAD

**Issue by Djacob502** [dji-sdk/Mobile-UILibrary-Android#13]
Using the panel - CameraSettingExposurePanel - the aperture setting is not scrolling when using the Aperture and manual mode. A small arrow shows up under the aperture but then quickly goes away. 

The ISO and shutter scrolls work correctly. 

I do not know if this is related, but when the AE button is clicked (dji.ui.widget.AutoExposureLockWidget) - the setting does not save itself. First the setting turns to locked, and but then becomes unlocked if the exposure panel switches to another setting such as manual. 

DJI android UI library 4.1.1
Android 7.0 - nVidia k1 shield. 
Phantom 4 pro
Android version 2.3.3

**Comment by talobin** [comment]
This problem should not exist in current version (4.3.2) any more.
Will go ahead and close this issue.
@Djacob502 please feel free to reopen if you find out the bug still exists.
Thanks
