### ISSUE TITLE
Native method not found: dji.midware.natives.SDKRelativeJNI.native_getUsbAccessoryAttachedString:()Ljava/lang/String; 

### ISSUE THREAD

**Issue by qqwoshiwuli** [dji-sdk/Mobile-UILibrary-Android#14]
java.lang.UnsatisfiedLinkError: Native method not found: dji.midware.natives.SDKRelativeJNI.native_getUsbAccessoryAttachedString:()Ljava/lang/String;

I have entered key, but I can't access APP，why?

**Comment by oliverou** [comment]
Hi @qqwoshiwuli, please provide the following infos for us to investigate your issue:

-  DJI Android SDK version you are using (Like Android SDK 3.4, etc)
-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)
-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)
-  Android Studio version you are using (Like Android Studio 2.2, etc)

Thanks!

**Comment by nthiang** [comment]
Hi DJI Team, 

I've seen many posts with this error that have no proper conclusion. Hopefully, we can finally get an answer here. 

I followed the [Android Studio Project Integration Tutorial](https://developer.dji.com/mobile-sdk/documentation/application-development-workflow/workflow-integrate.html#android-studio-project-integration), tried the [Mobile SDK Android sample code](https://github.com/dji-sdk/Mobile-SDK-Android) and so on and still arrived with the following error: 
**java.lang.UnsatisfiedLinkError: Native method not found: dji.midware.natives.SDKRelativeJNI.native_getUsbAccessoryAttachedString:()Ljava/lang/String;**

My environment is as follows: 

- DJI Android SDK - V4.2.1 (https://developer.dji.com/mobile-sdk/downloads/)
- DJI Product - Mavic Pro
- Android System/Device: Nexus 5 API 23 x86 Emulator Android 6.0 Marshmellow - it should work on the emulator. 
- Android Studio v2.3.3

**Comment by oliverou** [comment]
Hi @nthiang, the Android SDK 4.2.1 doesn't support X86 machince or Android Emulator, please use Android devices to test the sample app. We are still investigating this issue, will fix it in the future SDK version.

**Comment by nthiang** [comment]
Hi @oliverou, 

Thank you for your response and affirmation.

**Comment by talobin** [comment]
Will ahead and close this ticket now.
