### ISSUE TITLE
widgets unable to adjust width and height？

### ISSUE THREAD

**Issue by PanGuangwei** [dji-sdk/Mobile-UILibrary-Android#15]
#### Is this issue about bugs or crash issues of DJI Android UILibrary and Sample Code?

Yep, then please delete this template and provide the following infos for us to help investigate the issue:

-  Description of the issue.
-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)
-  Crash logs (If you can find it, it would be very helpful)
-  DJI Android UILibrary version you are using (Like Android UILibrary 4.0.1.1.0.0, etc)
-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)
-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)
-  Android Studio version you are using (Like Android Studio 2.2, etc)
-  Are you using UILibrary Sample Code (Yes/No)?
-  If the answer of previous one is No, please specify which elements of UILibrary are you using.

#### Is this issue about DJI iOS UILibrary and Sample Code?

Then this is the wrong place, please refer to the Mobile-UILibrary-iOS Github: <https://github.com/dji-sdk/Mobile-UILibrary-iOS/issues>

**Comment by talobin** [comment]
Will go ahead and close this issue.
If the problem still exists, please help us and fill out more information.
Thanks
