### ISSUE TITLE
New version of SDK 4.2

### ISSUE THREAD

**Issue by xxmaestroxx** [dji-sdk/Mobile-UILibrary-Android#16]
Hi everybody,

when do you expect the update of the mobile ui library because of the sdk update to 4.2?

Regards
xxmaestroxx

**Comment by oliverou** [comment]
Hi @xxmaestroxx, we may release the DJI UI Library 4.2 (With DJI Mobile SDK 4.2.1) within this week.

**Comment by talobin** [comment]
Closing this issue.
Our latest version is 4.3.2 as of now.
Thanks
