### ISSUE TITLE
Problem with UILibrary Android - Video Freeze

### ISSUE THREAD

**Issue by filthros** [dji-sdk/Mobile-UILibrary-Android#17]
Hello everyone,

I have problems when trying to run the sample application that provides the new version of UILibrary.

The problem is that I can not see the video in real time, sometimes the screen goes black and other times the video is displayed until the top status bar is updated.

I do not know what the problem is.

How can i fix it?

My aircraft is a M600 Pro with the latest firmware. Zenmuse X5 with the latest firmware and the lightbridge firmware is updated as well.

I'm using the latest Mobile-UILibrary-Android-4.2.1.

I am trying to deploy on a huawei mediapad m3 tablet with android version 6.0.

The version of Android studio is 2.3.3.

Any ideas?

Thank you very much.

**Comment by talobin** [comment]
Hi @filthros , this problem should be fixed in 4.3.2.
I will go ahead and close the issue.
If you still see the bug, please feel free to re-open .
Thank you.

**Comment by jayakrishnan1236** [comment]
I am facing the same issue. I am only able to see the black screen. It happens very often. 1 out of 5 times probably.
