### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by kwong93** [dji-sdk/Mobile-UILibrary-Android#18]
https://developer.dji.com/mobile-sdk/documentation/android-tutorials/UILibraryDemo.html

The link to the release aar for the ui library is broken. It was renamed from "android-uilib-release.aar" to "dji-uilibrary.aar". Please update the documentation.

**Comment by oliverou** [comment]
Hi @kwong93 , thanks for the feedbacks. The tutorial and sample code for Android UILibraryDemo are updated, please check them again.
