### ISSUE TITLE
duplicate entry of nineoldandroids

### ISSUE THREAD

**Issue by victor-fang** [dji-sdk/Mobile-UILibrary-Android#2]
Env:
Android studio 2.3.1

compile error:

Error:Execution failed for task ':Android:transformClassesWithJarMergingForRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/nineoldandroids/animation/Animator$AnimatorListener.class

**Comment by talobin** [comment]
@victor-fang does this still happen with the latest version of UILib?

Thanks
