### ISSUE TITLE
Roadmap for the UI library

### ISSUE THREAD

**Issue by Djacob502** [dji-sdk/Mobile-UILibrary-Android#21]
Not an issue but could DJI publish a roadmap on what we can expect in new capabilities for the UI library? Perhaps capabilities by quarter - roughly? 
I'm curious on how developed the UI library will become.

**Comment by zoemcateedji** [comment]
The roadmap is still evolving and we are not ready to release it at this time.  Thanks for your enthusiasm for the UI Library project!

**Comment by talobin** [comment]
Will go ahead and close this issue.
Thanks for the suggestion.
