### ISSUE TITLE
Object detection widget

### ISSUE THREAD

**Issue by kwong93** [dji-sdk/Mobile-UILibrary-Android#22]
Can we get a UI widget to show how close front and back with the sensors with distance?

https://forum44.djicdn.com/data/attachment/forum/201604/05/204342l1g6yl9j6bi9bgbn.jpg

**Comment by oliverou** [comment]
Hi @kwong93, currently, the UILibrary doesn't provide such UI widget. And even the DJI Android SDK doesn't support this feature yet.

**Comment by kwong93** [comment]
Wouldn't setVisionDetectionStateUpdatedCallback be the one to use? I can get the detection sectors and distance and warnings from that callback

**Comment by talobin** [comment]
I will go ahead and close this ticket.
One of our developer is working on adding this feature to UILibrary.
You can expect to see this in one of our coming releases.

**Comment by Mustafa9391** [comment]
Hello everyone, i'im using SDK 4.3.1, i want to detect obstacle so i use this code : DJISampleApplication.getAircraftInstance().getFlightController().getFlightAssistant().setVisionDetectionStateUpdatedCallback(new VisionDetectionState.Callback() {    @Override    public void onUpdate(@NonNull VisionDetectionState visionDetectionState) {        Log.d(TAG, "Distance Obstacle : " + visionDetectionState.getObstacleDistanceInMeters() +                ", Position : " + visionDetectionState.getPosition().toString() +                ", Warning : " + visionDetectionState.getSystemWarning().toString());    }});but doesn't work, it doesn't return anything, im using spark drone, and getFlightController().isFlightAssistantSupported(); return trueThank you
--

**Comment by Mustafa9391** [comment]
### Hello everyone, i'im using SDK 4.3.1, i want to detect obstacle so i use this code : 
`DJISampleApplication.getAircraftInstance().getFlightController().getFlightAssistant().setVisionDetectionStateUpdatedCallback(new VisionDetectionState.Callback() {`

 `@Override    public void onUpdate(@NonNull VisionDetectionState visionDetectionState) {        
Log.d(TAG, "Distance Obstacle : " + visionDetectionState.getObstacleDistanceInMeters() +                ", Position : " + visionDetectionState.getPosition().toString() +                ", Warning : " + visionDetectionState.getSystemWarning().toString());   
 }});`
but doesn't work, it doesn't return anything, im using spark drone, and `getFlightController().isFlightAssistantSupported();` 
### return true
Thank you
--
