### ISSUE TITLE
start waypoint mission with the takeoff widget

### ISSUE THREAD

**Issue by stephan-smets** [dji-sdk/Mobile-UILibrary-Android#25]
The samples give a simple explanation how to do minor modifications on the DJI widgets.

I would like to use the takeoff widget to start my own waypoint mission. But I do not understand how to start a mission (defined in the MainActivity class) from a custom DJI Widget class.

What is the correct way to interact with the MainActivity from a custom DJI widget?

**Comment by talobin** [comment]
@stephan-smets 
1. To change behavior of TakeOffWidget there are two ways:
- 1. Override `performTakeOffAction`, if you only want to change click behavior of taking off and keep behavior of AutoLand
- 2. Override onClick() method, if you want to change click behavior of the entire widget
2. There are many ways to "interact" with MainActivity. You should pick what is the most appropriate approach for your application:
 - 1. Make method inside MainActivity `public static`
 - 2. Use EventBus to send an Event from `TakeOffWidget`, listen to that even in `MainActivity` and do whatever you like.
 - 3. Other ways
As this is more of Android general question not UILibrary specific, I will go ahead and close the issue.
If you still have problem with `TakeOffWidget`  itself, you can reopen.
