### ISSUE TITLE
The FPVWidget is very unstable using this UILibrary on Phantom 4 Pro

### ISSUE THREAD

**Issue by GIS-HowardZhang** [dji-sdk/Mobile-UILibrary-Android#3]
FPVWidget is very unstable and the screen blurred badly when something is moving in front of the camera.  

But every time I press shutter button on remote controller, the FPV becomes quite clear at that moment. Then after a second it returns blurred. Using DJI GO4 and sdk3.5 is all good.

**Comment by Djacob502** [comment]
I wonder if this issue is dependent on the power in the tablet? I'm using the nVidia shield k1 tablet and the FPV widget runs properly without error.

**Comment by talobin** [comment]
@GIS-HowardZhang could you help us by giving the model of device, android version you are using?

Thanks

**Comment by GIS-HowardZhang** [comment]
@talobin 

Phantom 4 Pro
Android 6.0.1
Huawei Honor Pad 2

**Comment by talobin** [comment]
@GIS-HowardZhang 
This problem should be fixed with UILib 4.3.2.
Will go ahead and close the tickets
Please feel free to reopen if the bug still exists.
