### ISSUE TITLE
Not possible to build apk with UILibrary

### ISSUE THREAD

**Issue by xxmaestroxx** [dji-sdk/Mobile-UILibrary-Android#6]
Hey,

i got a problem if i want to build my apk.

The following error is thrown:
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/gson/stream/MalformedJsonException.class

That are my dependencies:
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile project(':dji-sdk')
    compile project(':dji-uilib-release-4.0.1.1.0.0')
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:design:25.3.1'
    compile 'com.android.support:recyclerview-v7:25.3.1'
    compile 'com.android.support:cardview-v7:25.3.1'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.google.android.gms:play-services-location:10.2.0'
    compile 'com.google.android.gms:play-services-places:10.2.0'
    compile 'com.google.android.gms:play-services-maps:10.2.0'
    compile 'com.google.android.gms:play-services-analytics:10.2.0'
    compile 'com.google.maps.android:android-maps-utils:0.4.4'
    compile 'com.google.guava:guava:20.0'
    compile 'commons-io:commons-io:2.5'
    compile 'org.jetbrains:annotations-java5:15.0'
    compile 'com.robinhood.spark:spark:1.1.2'
    compile 'com.opencsv:opencsv:3.8'
}

Can you help me to solve the problem, otherwise I'm not able to use the UI Library.

Regards
Maestro

**Comment by talobin** [comment]
Hi there,

Could you provide us the following info:
- Operating system you are running
- Android Studio version
- Gradle version

Also, have you tried to build the sample app?
https://github.com/dji-sdk/Mobile-UILibrary-Android/tree/master/sample

Thank you.

**Comment by xxmaestroxx** [comment]
Operating PC System: Windows 10
Android Studio version: 2.3.2
Gradle version: 2.3.2

Tablet Android version: 5.0.1

But the gradle build is not working, therefore i think the Android version is not really relevant.

**Comment by xxmaestroxx** [comment]
So i tried to build the UILib Sample project on my system.
That was possible so i can install the UILib sample on my device.

At the moment where i add the DJISDK to the sample project or other way around open the DJI SDK Sample project and add the UI Lib Android Studio is not able to build the APK by getting the error message from above.

So i think there is a dependency problem between your both libraries.

Regards
xxmaestroxx

**Comment by xxmaestroxx** [comment]
Another hint,

if i remove the gson dependency from the SDK i got the following error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: dji/midware/BuildConfig.class

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Best regards

**Comment by xxmaestroxx** [comment]
Hey guys,

i would really like to use your UI library but unfortunately i cannot put the SDK and the UI library in the same application.

Then it's still not possible for me to build the APK with the following error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: dji/midware/BuildConfig.class

Can you please check that and i it's working on your environment, can you upload maybe an example project where both libraries are contained, so i can see what is wrong in my configuration?

Best regards
xxmaestroxx

**Comment by zoemcateedji** [comment]
The UIl library already includes the SDK, so you shouldn't have to include the SDK a second time in your project.  That would explain why you are getting messages about duplicates.

**Comment by xxmaestroxx** [comment]
Jep thanks for that answer, i found the same answer yesterday evening within the DJI Forum, it would be so easy if this statement is contained within the tutorial!!!!!

Regards
xxmaestroxx
