### ISSUE TITLE
PreFlightStatusWidget  message建议定义到string.xml文件中

### ISSUE THREAD

**Issue by xbting** [dji-sdk/Mobile-UILibrary-Android#7]
现在PreFlightStatusWidget显示内容都是英文的，想改成中文，看了下发现这些message都是定义在FPVTipLogic类代码中的，建议这些提示定义到string.xml文件中，这样开发者这可以方便的修改

**Comment by oliverou** [comment]
Hi @xbting, currently，we don't support localization in PreFlightStatusWidget. You can only use English for this widget.
