### ISSUE TITLE
MF/AF widget and the AE lock behavior

### ISSUE THREAD

**Issue by Djacob502** [dji-sdk/Mobile-UILibrary-Android#8]
When clicking the manual focus icon, then shouldn't a slider be presented to the user to allow the user to choose between close-up and infinity focus as in the DJI Go 4 app? Or is this behavior left to us to include. Currently after choosing MF, the autofocus green target box displays on the screen and this target box should not display when choosing MF. 

Also after choosing the AE lock, and the selecting the yellow AE icon, a message should display that the exposure cannot be changed. Instead the yellow AE target continues to display. 

Using DJI UI version 4.1.1
nVidia k1 shield. 
Android 7.0 
Android Studio - 2.3.3
Using the UI widgets but not the sample code.

**Comment by talobin** [comment]
@Djacob502 
4.3.2 should fix this problem.
Will go ahead and close the issue.
Please feel free to reopen if the bug still exists.
