### ISSUE TITLE
Problem with Asus Memo Pad 8

### ISSUE THREAD

**Issue by xxmaestroxx** [dji-sdk/Mobile-UILibrary-Android#9]
Hey everybody,

i could get your sample ui app running on my nexus 5 without any problems!

But for developing i normally use a Asus Memo Pad8, with the following features:

- Intel® Atom™ Z3560 up to 1.83 GHz, Quad-Core
- 2GB Ram

Unfortunately i get always directly after startup an error message that the app crashed.
Within the log i just get the following information in Android Studio:

```
06-10 15:41:58.916 21444-21444/? I/art: Late-enabling -Xcheck:jni
06-10 15:41:58.976 21444-21444/com.dji.ui.sample W/ResourcesManager: Asset path '/system/framework/com.android.future.usb.accessory.jar' does not exist or contains no resources.
06-10 15:41:58.986 21444-21444/com.dji.ui.sample V/Monotype: SetAppTypeFace- try to flip, app = com.dji.ui.sample
06-10 15:41:58.986 21444-21444/com.dji.ui.sample V/Monotype:     Typeface getFontPathFlipFont - systemFont = default#default
06-10 15:41:58.996 21444-21444/com.dji.ui.sample W/linker: libffmpeg.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
06-10 15:41:58.996 21444-21444/com.dji.ui.sample A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x700c3690 in tid 21444 (m.dji.ui.sample)
06-10 15:41:59.006 21444-21454/com.dji.ui.sample A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x12c04001 in tid 21454 (JDWP)
```

Hopefully you can help my with my problem!

Regards
xxmaestroxx

**Comment by oliverou** [comment]
Currently we have some compatibility issues with x86 so architecture. Could you please provide more information of your devices and project, such as Android Platform version, build version, compile version and target version for us to investigate to issue? Thanks!

**Comment by xxmaestroxx** [comment]
Hey Oliverou,

about the tablet you can gather all needed information here: 
 - https://www.asus.com/Tablets/ASUS_MeMO_Pad_8_ME581CL/specifications/

Additionally some informations from my side:
- current android version: 5.0.1
- compileSdkVersion/targetSdkVersion 25
- minSdkVersion 19

Regards
Bastian

**Comment by talobin** [comment]
Hi @xxmaestroxx version 4.3.2 should fix this issue.
Will go ahead and close the issue.
Please feel free to reopen if the bug still exists.
